name: Hello world
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "This is my {{ vars.MY_NAME }} workflow"
      - name: Docker secrets
        run: echo "Docker username is ${{ secrets.DOCKER_USERNAME }}"
  
      
